/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Gain API
 * OpenAPI spec version: 1.0.0
 */
import type { GetPing200Message } from './getPing200Message'

export type GetPing200 = {
  message: GetPing200Message
  timestamp: string
}
