/**
 * Generated by orval v7.5.0 🍺
 * Do not edit manually.
 * Gain API
 * OpenAPI spec version: 1.0.0
 */

export type GetPing200Message = (typeof GetPing200Message)[keyof typeof GetPing200Message]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetPing200Message = {
  pong: 'pong',
} as const
